version: '3'

services:
  doctissimo-api-nginx:
    container_name: doctissimo-api-nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './doctissimo-api:/var/www/app'
      - './doctissimo-api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8081:80
    depends_on:
      - doctissimo-api-php

  doctissimo-api-php:
    container_name: doctissimo-api-php
    build:
      context: .
      dockerfile: doctissimo-api/docker/php/Dockerfile
    restart: on-failure
    env_file:
      - doctissimo-api/.env
    user: 1000:1000
    volumes:
      - ./doctissimo-api:/var/www/app

  doctissimo-api-mysql:
    container_name: doctissimo-api-mysql
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: doctissimo

  doctissimo-front-nginx:
    container_name: doctissimo-front-nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './doctissimo-front:/var/www/app'
      - './doctissimo-front/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - 8082:80
    depends_on:
      - doctissimo-front-php

  doctissimo-front-php:
    container_name: doctissimo-front-php
    build:
      context: .
      dockerfile: doctissimo-front/docker/php/Dockerfile
    restart: on-failure
    env_file:
      - doctissimo-front/.env
    user: 1000:1000
    volumes:
      - ./doctissimo-front:/var/www/app